FROM nginx:alpine

# Copier les fichiers frontend
COPY frontend/ /usr/share/nginx/html/

# Copier la configuration NGINX personnalisée
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]