name: Générer Graphe Statique

on:
  push:
    paths:
      - 'mon_project/**'  # ← adapte au dossier de code
      - 'scripts/static_call_graph.py'

jobs:
  build-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer dépendances
        run: pip install networkx

      - name: Générer graphe d'appels
        run: python scripts/static_call_graph.py

      - name: Commit & Push call_graph.json
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add call_graph.json
          git commit -m "Update static call graph"
          git push
        continue-on-error: true  # Évite d'exploser si rien n’a changé
