name: Générer Graphe Statique et Artefacts

on:
  push:
    paths:
      - 'backend/**'
      - 'scripts/static_call_graph.py'
      - '.github/workflows/generate-callgraph.yml'

jobs:
  build-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install networkx pygraphviz cairosvg
          sudo apt-get update -y
          sudo apt-get install -y graphviz

      - name: Generate call_graph.json
        run: python scripts/static_call_graph.py

      - name: Generate SVG and PNG
        run: |
          python -c "import json, subprocess, networkx as nx; from networkx.drawing.nx_agraph import write_dot; data=json.load(open('call_graph.json')); G=nx.node_link_graph(data, directed=True); write_dot(G,'call_graph.dot'); subprocess.run(['dot','-Tsvg','call_graph.dot','-o','call_graph.svg'], check=True); subprocess.run(['dot','-Tpng','call_graph.dot','-o','call_graph.png'], check=True)"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: call-graph-assets
          path: |
            call_graph.json
            call_graph.svg
            call_graph.png
