name: Générer Graphe Statique et Artefacts

on:
  push:
    paths:
      - 'backend/**'
      - 'scripts/static_call_graph.py'
      - '.github/workflows/generate-callgraph.yml'

jobs:
  build-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/static_call_graph.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Graphviz
        uses: dawidd6/setup-graphviz@v1

      - name: Install Python dependencies
        run: pip install networkx pygraphviz cairosvg

      - name: Generate call_graph.json
        run: python scripts/static_call_graph.py

      - name: Generate call_graph images
        run: |
          python -c "import json, networkx as nx; from networkx.drawing.nx_agraph import to_agraph; data=json.load(open('call_graph.json')); G=nx.node_link_graph(data, directed=True); A=to_agraph(G); A.write('call_graph.dot'); A.draw('call_graph.svg', format='svg'); A.draw('call_graph.png', format='png')"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: call-graph-assets
          path: |
            call_graph.json
            call_graph.dot
            call_graph.svg
            call_graph.png
